[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false
rust-version.workspace = true

[dependencies]
ts-rs = { workspace = true }
engawa-format = { workspace = true }
engawa-kernel = { workspace = true }
engawa-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
